# Generated by Django 5.0.3 on 2024-05-20 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paliative_care_app', '0002_accessory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paliative_care_app.accessory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paliative_care_app.patient')),
            ],
        ),
    ]
