# Generated by Django 5.0.3 on 2024-05-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paliative_care_app', '0003_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
