# Generated by Django 5.0.3 on 2024-05-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paliative_care_app', '0004_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
            ],
        ),
    ]
