# Generated by Django 5.0.3 on 2024-05-23 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paliative_care_app', '0006_doctor_schedule_doctor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_schedule_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paliative_care_app.doctor_schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paliative_care_app.patient')),
            ],
        ),
    ]
