# Generated by Django 5.0.3 on 2024-05-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paliative_care_app', '0007_doctor_schedule_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_schedule_booking',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
