# Generated by Django 5.0.3 on 2024-05-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paliative_care_app', '0008_alter_doctor_schedule_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=255)),
            ],
        ),
    ]
