# Generated by Django 5.0.3 on 2024-05-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paliative_care_app', '0011_alter_prescription_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription',
            field=models.FileField(upload_to='document/'),
        ),
    ]
