# Generated by Django 5.0.3 on 2024-06-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paliative_care_app', '0012_alter_prescription_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('Details', models.CharField(max_length=255)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
            ],
        ),
    ]
