# Generated by Django 5.0.3 on 2024-06-02 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paliative_care_app', '0013_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reports', models.FileField(upload_to='document/')),
                ('Doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paliative_care_app.doctor')),
            ],
        ),
    ]
