# Generated by Django 5.0.3 on 2024-06-02 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paliative_care_app', '0014_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='patient_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paliative_care_app.patient'),
            preserve_default=False,
        ),
    ]
