# Generated by Django 5.0.3 on 2024-06-03 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paliative_care_app', '0015_reports_patient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('request_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paliative_care_app.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paliative_care_app.patient')),
            ],
        ),
    ]
